export const GET_ALL_BREEDS = "GET_ALL_BREEDS";
export const GET_BREED_BY_ID = "GET_BREED_BY_ID";
export const GET_ALL_TEMPERAMENTS = "GET_ALL_TEMPERAMENTS";
export const CARGAR_TEMEPERAMENTOS = "CARGAR_TEMEPERAMENTOS";
export const GET_BREEDS_BY_NAME = "GET_BREEDS_BY_NAME";
export const GET_BREEDS_BY_TEMPERAMENT = "GET_BREEDS_BY_TEMPERAMENT";
