export const GET_ALL_BREEDS = "GET_ALL_BREEDS";
export const GET_BREED_BY_ID = "GET_BREED_BY_ID";
export const GET_ALL_TEMPERAMENTS = "GET_ALL_TEMPERAMENTS";
export const CARGAR_TEMEPERAMENTOS = "CARGAR_TEMEPERAMENTOS";
